---
- name: Remove old cassandra apt sources.list file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/www_apache_org_dist_cassandra_debian.list
    state: absent

- name: Remove cassandra apt signing keys from default apt keyring
  ansible.builtin.apt_key:
    id: "{{ item }}"
    keyring: /etc/apt/trusted.gpg
    state: absent
  loop: "{{ cassandra_apt_key_fingerprints }}"

- name: Remove old cassandra apt repository entry
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/cassandra.gpg]
      https://www.apache.org/dist/cassandra/debian
      {{ cassandra_series_version }} main
    filename: cassandra
    update_cache: no
    state: absent

- name: Remove cassandra apt signing key from /usr/share/keyrings
  ansible.builtin.file:
    path: /usr/share/keyrings/cassandra.gpg
    state: absent

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Import cassandra packaging GPG signing key
  ansible.builtin.apt_key:
    url: https://www.apache.org/dist/cassandra/KEYS
    keyring: /etc/apt/keyrings/cassandra.gpg
    state: present

- name: Add cassandra repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/cassandra.gpg]
      https://www.apache.org/dist/cassandra/debian
      {{ cassandra_series_version }} main
    filename: cassandra
    state: present

- name: Install cassandra packages
  ansible.builtin.apt:
    pkg:
      - default-jre-headless
      - cassandra
    state: present

# Warn users that /etc/cassandra/cassandra.yaml is managed by ansible (even
# though only some of the lines actually are).
- name: Mark /etc/cassandra/cassandra.yaml as managed by ansible
  ansible.builtin.lineinfile:
    dest: /etc/cassandra/cassandra.yaml
    line: "# Ansible managed"
    state: present
    insertbefore: BOF

# the influxdb config file moves quickly, so just update the known issues
- name: Configure /etc/cassandra/cassandra.yaml
  ansible.builtin.lineinfile:
    dest: /etc/cassandra/cassandra.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^cluster_name:"
      line: "cluster_name: '{{ cassandra_cluster_name }}'"
    - regexp: "^listen_address:"
      line: "listen_address: {{ cassandra_listen_address }}"
    - regexp: "^rpc_address:"
      line: "rpc_address: {{ cassandra_rpc_address }}"
    - regexp: "^rpc_port:"
      line: "rpc_port: {{ cassandra_rpc_port }}"
  loop_control:
    label: "{{ item.line }}"
  notify: restart cassandra
